apiVersion: v1
kind: Service
metadata:
  name: user-db-service
  namespace: tripgen-dev
  labels:
    app: user-db
    component: database
    service: user-service
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: user-db