apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-db-pvc
  namespace: tripgen-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: managed