apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: location-db-pvc
  namespace: tripgen-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi  # PostGIS 및 공간 데이터를 위한 추가 공간
  storageClassName: managed