---
apiVersion: v1
kind: ConfigMap
metadata:
  name: location-redis-config
  namespace: tripgen-dev
data:
  redis.conf: |
    # Redis 7.0 설정
    port 6379
    bind 0.0.0.0
    protected-mode no
    
    # 메모리 설정 (위치 데이터 캐시용)
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    
    # 영속성 비활성화 (개발환경)
    save ""
    appendonly no
    
    # 로그 설정
    loglevel notice
    logfile ""
    
    # 성능 최적화
    tcp-keepalive 300
    timeout 0
    
    # 지리 데이터 최적화 설정
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    
    # 검색 최적화를 위한 메모리 정책
    lazyfree-lazy-eviction yes
    lazyfree-lazy-expire yes
---
apiVersion: v1
kind: Service
metadata:
  name: location-redis-service
  namespace: tripgen-dev
  labels:
    app: location-redis
spec:
  selector:
    app: location-redis
  ports:
    - port: 6382
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-redis
  namespace: tripgen-dev
  labels:
    app: location-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-redis
  template:
    metadata:
      labels:
        app: location-redis
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
        command:
        - redis-server
        - /usr/local/etc/redis/redis.conf
        resources:
          requests:
            memory: "384Mi"
            cpu: "150m"
          limits:
            memory: "768Mi"
            cpu: "400m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-config
        configMap:
          name: location-redis-config