---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-redis-config
  namespace: tripgen-dev
data:
  redis.conf: |
    # Redis 7.0 설정
    port 6379
    bind 0.0.0.0
    protected-mode no
    
    # 메모리 설정
    maxmemory 1024mb
    maxmemory-policy allkeys-lru
    
    # 영속성 비활성화 (개발환경)
    save ""
    appendonly no
    
    # 로그 설정
    loglevel notice
    logfile ""
    
    # 성능 최적화
    tcp-keepalive 300
    timeout 0
    
    # 압축 설정 (여행 데이터 최적화)
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
---
apiVersion: v1
kind: Service
metadata:
  name: trip-redis-service
  namespace: tripgen-dev
  labels:
    app: trip-redis
spec:
  selector:
    app: trip-redis
  ports:
    - port: 6380
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-redis
  namespace: tripgen-dev
  labels:
    app: trip-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-redis
  template:
    metadata:
      labels:
        app: trip-redis
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
        command:
        - redis-server
        - /usr/local/etc/redis/redis.conf
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-config
        configMap:
          name: trip-redis-config