apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-db
  namespace: tripgen-dev
  labels:
    app: trip-db
    component: database
    service: trip-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-db
  template:
    metadata:
      labels:
        app: trip-db
        component: database
        service: trip-service
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trip-db-secret
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: trip-db-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U tripgen_trip -d tripgen_trip_db -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U tripgen_trip -d tripgen_trip_db -h 127.0.0.1 -p 5432
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: trip-db-pvc
      - name: init-sql
        configMap:
          name: trip-db-init-sql
      restartPolicy: Always