apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: tripgen-dev
type: Opaque
data:
  # Base64 인코딩된 값 (실제 운영시 변경 필요)
  POSTGRES_PASSWORD: dHJpcGdlbl91c2VyXzEyMw==  # tripgen_user_123