spring:
  application:
    name: ai-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:ai_db}
    username: ${DB_USERNAME:ai_user}
    password: ${DB_PASSWORD:ai_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        default_schema: public
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis_pass}
      timeout: ${REDIS_TIMEOUT:10s}
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 5

  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL:3600s}
      cache-null-values: false

  cloud:
    azure:
      servicebus:
        enabled: true
        connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING:}
        pricing-tier: standard

server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1/ai}

security:
  jwt:
    secret: ${JWT_SECRET:TripGenAI2025SecretKeyForJWTTokenGeneration}
    expiration: 3600000 # 1 hour

# AI Service Configurations
ai:
  openai:
    api-key: ${OPENAI_API_KEY}
    model: ${OPENAI_MODEL:gpt-4}
    max-tokens: ${OPENAI_MAX_TOKENS:4000}
    temperature: ${OPENAI_TEMPERATURE:0.7}
    timeout: ${OPENAI_TIMEOUT:60s}
  
  claude:
    api-key: ${CLAUDE_API_KEY}
    model: ${CLAUDE_MODEL:claude-3-opus-20240229}
    max-tokens: ${CLAUDE_MAX_TOKENS:4000}
    timeout: ${CLAUDE_TIMEOUT:60s}

  job:
    schedule-generation:
      timeout: ${AI_SCHEDULE_TIMEOUT:300s} # 5 minutes
      max-retries: ${AI_SCHEDULE_MAX_RETRIES:3}
      queue-name: ${AI_SCHEDULE_QUEUE:ai-schedule-jobs}
    recommendation:
      timeout: ${AI_RECOMMENDATION_TIMEOUT:180s} # 3 minutes
      max-retries: ${AI_RECOMMENDATION_MAX_RETRIES:3}
      queue-name: ${AI_RECOMMENDATION_QUEUE:ai-recommendation-jobs}

# External Service URLs
external-services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081/api/v1/users}
    connect-timeout: ${USER_SERVICE_CONNECT_TIMEOUT:5s}
    read-timeout: ${USER_SERVICE_READ_TIMEOUT:30s}
  
  location-service:
    url: ${LOCATION_SERVICE_URL:http://localhost:8082/api/v1/locations}
    connect-timeout: ${LOCATION_SERVICE_CONNECT_TIMEOUT:5s}
    read-timeout: ${LOCATION_SERVICE_READ_TIMEOUT:30s}
  
  weather-service:
    url: ${WEATHER_SERVICE_URL:http://localhost:8082/api/v1/locations/weather}
    connect-timeout: ${WEATHER_SERVICE_CONNECT_TIMEOUT:5s}
    read-timeout: ${WEATHER_SERVICE_READ_TIMEOUT:30s}

# Feign Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000
        loggerLevel: basic
  compression:
    request:
      enabled: true
    response:
      enabled: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    com.unicorn.tripgen.ai: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:DEBUG}
    org.hibernate.type: ${LOG_LEVEL_SQL_TYPE:TRACE}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:logs/ai-service.log}

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false

external-services:
  user-service:
    url: ${USER_SERVICE_URL}
  location-service:
    url: ${LOCATION_SERVICE_URL}
  weather-service:
    url: ${WEATHER_SERVICE_URL}

logging:
  level:
    com.unicorn.tripgen.ai: ${LOG_LEVEL_APP:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:WARN}
    org.hibernate: ${LOG_LEVEL_HIBERNATE:WARN}