# User Service Application Configuration

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 10
  error:
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: user-service
  
  profiles:
    active: dev
    
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tripgen_user}
    username: ${DB_USERNAME:tripgen_user}
    password: ${DB_PASSWORD:tripgen_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
    open-in-view: false
    
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:tripgen_redis_password}
      database: ${REDIS_DATABASE:0}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms
          
  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL:3600}s
      cache-null-values: false
      
  # Multipart Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 1MB
      
  # Jackson Configuration
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
      accept-empty-string-as-null-object: true

# Logging Configuration
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.unicorn.tripgen: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/user-service.log
    max-size: 100MB
    max-history: 30

# Application Specific Configuration
app:
  jwt:
    secret: ${JWT_SECRET:tripgen-jwt-secret-key-very-long-and-secure-for-production-use-only-change-this-in-production}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600}  # 1 hour in seconds
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800}  # 7 days in seconds
    
  file:
    upload-path: ${FILE_UPLOAD_PATH:/app/uploads}
    base-url: ${FILE_BASE_URL:http://localhost:8081}
    max-size: ${FILE_MAX_SIZE:5242880}  # 5MB in bytes
    
  security:
    max-login-attempts: ${MAX_LOGIN_ATTEMPTS:5}
    account-lock-duration-minutes: ${ACCOUNT_LOCK_DURATION_MINUTES:30}
    password-min-length: ${PASSWORD_MIN_LENGTH:8}
    
# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  health:
    db:
      enabled: true
    redis:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      service: user-service
      
# OpenAPI Documentation
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.unicorn.tripgen.user.controller
  
---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
      
  # H2 Database for development (optional)
  # datasource:
  #   url: jdbc:h2:mem:tripgen_user_dev
  #   username: sa
  #   password: 
  #   driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
logging:
  level:
    com.unicorn.tripgen: DEBUG
    org.springframework.security: DEBUG
    
app:
  jwt:
    secret: dev-jwt-secret-key-for-development-only
    
---
# Production Profile  
spring:
  config:
    activate:
      on-profile: prod
      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
logging:
  level:
    root: WARN
    com.unicorn.tripgen: INFO
    org.springframework.security: WARN
    
app:  
  file:
    base-url: https://api.tripgen.com
    
management:
  endpoint:
    health:
      show-details: never