# User Service Application Configuration

server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 10
  error:
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: user-service
  
  profiles:
    active: dev
    
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/tripgen_user
    username: tripgen_user
    password: tripgen_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    open-in-view: false
    
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      password: tripgen_redis_password
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms
          
  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600s
      cache-null-values: false
      
  # Multipart Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 1MB
      
  # Jackson Configuration
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
      accept-empty-string-as-null-object: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.unicorn.tripgen: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/user-service.log
    max-size: 100MB
    max-history: 30

# Application Specific Configuration
app:
  jwt:
    secret: tripgen-jwt-secret-key-very-long-and-secure-for-production-use-only-change-this-in-production
    access-token-expiration: 3600  # 1 hour in seconds
    refresh-token-expiration: 604800  # 7 days in seconds
    
  file:
    upload-path: /app/uploads
    base-url: http://localhost:8081
    max-size: 5242880  # 5MB in bytes
    
  security:
    max-login-attempts: 5
    account-lock-duration-minutes: 30
    password-min-length: 8
    
# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  health:
    db:
      enabled: true
    redis:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      service: user-service
      
# OpenAPI Documentation
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.unicorn.tripgen.user.controller
  
---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
      
  # H2 Database for development (optional)
  # datasource:
  #   url: jdbc:h2:mem:tripgen_user_dev
  #   username: sa
  #   password: 
  #   driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
logging:
  level:
    com.unicorn.tripgen: DEBUG
    org.springframework.security: DEBUG
    
app:
  jwt:
    secret: dev-jwt-secret-key-for-development-only
    
---
# Production Profile  
spring:
  config:
    activate:
      on-profile: prod
      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
logging:
  level:
    root: WARN
    com.unicorn.tripgen: INFO
    org.springframework.security: WARN
    
app:  
  file:
    base-url: https://api.tripgen.com
    
management:
  endpoint:
    health:
      show-details: never